-- @@@LIMIT, OFFSET@@@
-- select * from film limit 20
-- 20 adet film gösterir
-- select title, rental_rate from film where rental_rate =4.99 order by length limit 20
-- select * from film where replacement_cost=14.99 and rental_rate=0.99 order by length desc limit 7
-- select * from country offset 6 limit 10
-- ilk 6 veriyi geçip sonraki 10 veriyi gösterir (7-17 arası)
-- select * from actor where first_name = 'Penelope' order by last_name offset 2 limit 1
-- ...

-- 1)film tablosunda bulunan ve film ismi (title) 'n' karakteri ile biten en uzun (length) 5 filmi sıralayınız.
-- select title, length from film where title like '%n' order by length desc limit 5
-- 2)film tablosunda bulunan ve film ismi (title) 'n' karakteri ile biten en kısa (length) ikinci(6,7,8,9,10) 5 filmi(6,7,8,9,10) sıralayınız.
-- select title, length from film where title like '%n' order by length desc offset 5 limit 5
-- 3)customer tablosunda bulunan last_name sütununa göre azalan yapılan sıralamada store_id 1 olmak koşuluyla ilk 4 veriyi sıralayınız.
-- select last_name, store_id from customer where store_id ='1' order by last_name desc limit 4